spring:
  application:
    name: Proyecto1Ruben-back
  datasource:
    url: jdbc:sqlite:src/main/resources/db/ruben_db.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: perezperezrodolfo550@gmail.com
    password: gfmt yugo ffdi qibr
    properties:
       mail:
         smtp:
           auth: true
           starttls:  
             enable: true