spring:
  application:
    name: Proyecto1Ruben-back
  datasource:
    url: jdbc:sqlite:src/main/resources/db/ruben_db.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true